window.TIMELINE_MODULES = {
  qm2: {
    label: "Quantum Mechanics 2",
    shortLabel: "QM2",
    accent: "#7f6ca8",
    courseId: "qm2",
    deadline: "2026-05-12",
    deadlineLabel: "12 May 2026",
    confidence: 60,
  },
  condensed: {
    label: "Condensed Matter Physics",
    shortLabel: "Condensed",
    accent: "#b85d58",
    courseId: "condensed",
    deadline: "2026-05-20",
    deadlineLabel: "20 May 2026",
    confidence: 20,
  },
  nano: {
    label: "Fundamentals of Nanotechnology",
    shortLabel: "Nano",
    accent: "#bf7f31",
    courseId: "nano",
    deadline: "2026-05-21",
    deadlineLabel: "21 May 2026",
    confidence: 50,
  },
  grcosmo: {
    label: "General Relativity and Cosmology",
    shortLabel: "GR/Cosmology",
    accent: "#628172",
    courseId: "relativity",
    deadline: "2026-05-27",
    deadlineLabel: "27 May 2026",
    confidence: 0,
  },
  admin: {
    label: "Admin",
    shortLabel: "Admin",
    accent: "#667085",
    courseId: "",
    deadline: "2026-05-27",
    deadlineLabel: "27 May 2026",
    confidence: 0,
  },
};

window.TIMELINE_PHASES = [
  {
    id: "phase-1-before-qm2",
    title: "Phase 1: 5-12 May",
    goal: "QM maintenance, one GR foundation day, and Condensed Topics 10-12 before QM2.",
  },
  {
    id: "phase-2-condensed-nano-war-week",
    title: "Phase 2: 13-21 May",
    goal: "Condensed follows the 2025/v3 3-day pass plan; Nano stays as light Section A maintenance until the Condensed exam is done.",
  },
  {
    id: "phase-3-gr-rescue",
    title: "Phase 3: 22-27 May",
    goal: "Full GR/Cosmology rescue week: read each week, do matching problems, then anchor past-paper questions.",
  },
];

window.TIMELINE_TASKS = [
  {
    id: "timeline-2026-05-05-qm2-post-mock-perturbation",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-05",
    moduleId: "qm2",
    priority: "Critical",
    type: "Post-Mock Repair",
    estimatedMinutes: 120,
    title: "Perturbation method recognition drill",
    details: [
      "Perturbation method recognition drill",
      "Redo one degenerate perturbation setup",
      "Add mistakes to QM2 Things I Keep Forgetting",
    ],
    tags: ["QM2", "Post-Mock", "Critical"],
  },
  {
    id: "timeline-2026-05-05-condensed-topic-10",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-05",
    moduleId: "condensed",
    priority: "Critical",
    type: "Concept",
    estimatedMinutes: 150,
    title: "Topic 10: Free electron gas",
    details: [
      "Focus: Drude theory, Hall voltage, AC transport overview, 2D free electron gas, DOS, energy of free electron gas",
      "Make rough Topic 10 formula/method sheet",
    ],
    tags: ["Condensed", "Topic 10", "Critical"],
  },
  {
    id: "timeline-2026-05-05-gr-vector-transformations",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-05",
    moduleId: "grcosmo",
    priority: "Light",
    type: "Concept",
    estimatedMinutes: 30,
    title: "Week 2 preview: vector transformation notes",
    details: ["Read the Week 2/revision-lecture notes on vector transformations"],
    tags: ["GR", "Week 2", "Optional"],
  },
  {
    id: "timeline-2026-05-06-gr-week-2-3-rust-repair",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-06",
    moduleId: "grcosmo",
    priority: "Critical",
    type: "Week-Based Study",
    estimatedMinutes: 120,
    title: "GR Week 2/3 rust repair",
    details: [
      "Read relevant lecture/chapter notes on manifolds, vectors, tensor transformations, metrics, and Christoffels",
      "Reproduce scalar/vector/basis transformation rules from revision lecture",
      "Do the matching problem sheet section if available",
    ],
    tags: ["GR", "Week 2", "Week 3", "Revision Lecture", "Critical"],
  },
  {
    id: "timeline-2026-05-06-gr-week-4-geodesic-repair",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-06",
    moduleId: "grcosmo",
    priority: "Critical",
    type: "Week-Based Study",
    estimatedMinutes: 120,
    title: "GR Week 4 geodesic repair",
    details: [
      "Read lecture/chapter notes on least-action geodesics",
      "Metric -> Lagrangian -> Euler-Lagrange -> equations of motion",
      "Do matching problem sheet section if available",
    ],
    tags: ["GR", "Week 4", "Geodesics", "Lecturer Hint", "Critical"],
  },
  {
    id: "timeline-2026-05-06-qm2-wkb-maintenance",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-06",
    moduleId: "qm2",
    priority: "Critical",
    type: "Maintenance",
    estimatedMinutes: 60,
    title: "WKB quartic repair",
    details: ["Redo setup and scaling once"],
    exact: ["QMII_6CCP3221_Mock.pdf - Section A Q1.5"],
    tags: ["QM2", "WKB", "Mock"],
  },
  {
    id: "timeline-2026-05-07-qm2-variational-repair",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-07",
    moduleId: "qm2",
    priority: "Critical",
    type: "Post-Mock Repair",
    estimatedMinutes: 120,
    title: "Variational Gaussian repair",
    details: [
      "Variational Gaussian repair",
      "Ladder operator ordering drill",
      "Redo one short Section A-style recognition set",
    ],
    exact: ["QMII_6CCP3221_Mock.pdf - Section B Q3(a)-(e)"],
    tags: ["QM2", "Variational", "Ladder Operators"],
  },
  {
    id: "timeline-2026-05-07-condensed-topic-11",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-07",
    moduleId: "condensed",
    priority: "Critical",
    type: "Concept",
    estimatedMinutes: 180,
    title: "Topic 11: Electronic bands / Fermi surfaces / insulators vs metals",
    details: [
      "Focus: Bloch theorem, electron dynamics, translational invariance, nearly-free electrons, graphene basics",
      "Make rough Topic 11 method sheet",
    ],
    tags: ["Condensed", "Topic 11", "Bands", "Critical"],
  },
  {
    id: "timeline-2026-05-07-gr-vector-recall",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-07",
    moduleId: "grcosmo",
    priority: "Light",
    type: "Recall",
    estimatedMinutes: 20,
    title: "Week 2 recall: vector transformation derivation",
    details: ["Redraw the Week 2 vector transformation derivation from memory"],
    tags: ["GR", "Week 2", "Optional"],
  },
  {
    id: "timeline-2026-05-08-qm2-time-dependent-spin",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-08",
    moduleId: "qm2",
    priority: "Critical",
    type: "Post-Mock Repair",
    estimatedMinutes: 120,
    title: "Time-dependent perturbation and spin repair",
    details: [
      "Time-dependent perturbation short drill",
      "Spin coupling repair",
      "Read QM2 Things I Keep Forgetting",
    ],
    exact: [
      "QMII_6CCP3221_Mock.pdf - Section A Q1.6",
      "QMII_6CCP3221_Mock.pdf - Section B Q2(a)-(e)",
    ],
    tags: ["QM2", "Time-Dependent Perturbation", "Spin"],
  },
  {
    id: "timeline-2026-05-08-condensed-topic-12",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-08",
    moduleId: "condensed",
    priority: "Critical",
    type: "Concept",
    estimatedMinutes: 180,
    title: "Topic 12: Optics, semiconductors, devices",
    details: [
      "Focus: absorption/band gap, dielectric constant and colour, effective mass, carrier concentration, Hall effect in semiconductors, law of mass action",
      "Make rough Topic 12 sheet",
    ],
    tags: ["Condensed", "Topic 12", "Critical"],
  },
  {
    id: "timeline-2026-05-09-qm2-maintenance",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-09",
    moduleId: "qm2",
    priority: "Critical",
    type: "Maintenance",
    estimatedMinutes: 60,
    title: "Perturbation recognition quick drill",
    details: ["Perturbation recognition quick drill", "10-15 min formula sheet review"],
    tags: ["QM2", "Maintenance"],
  },
  {
    id: "timeline-2026-05-10-qm2-mock-repair",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-10",
    moduleId: "qm2",
    priority: "Critical",
    type: "Mock Repair",
    estimatedMinutes: 120,
    title: "Mock repair sheet",
    details: ["Redo exact weak mock questions: WKB Q1.5, time-dependent Q1.6, variational B3 if needed"],
    exact: [
      "QMII_6CCP3221_Mock.pdf - Section A Q1.5",
      "QMII_6CCP3221_Mock.pdf - Section A Q1.6",
      "QMII_6CCP3221_Mock.pdf - Section B Q3(a)-(e)",
    ],
    tags: ["QM2", "Mock", "Critical"],
  },
  {
    id: "timeline-2026-05-11-qm2-final-review",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-11",
    moduleId: "qm2",
    priority: "Critical",
    type: "Final Review",
    estimatedMinutes: 210,
    title: "QM2 final formula/method sheet",
    details: [
      "Read QM2 Things I Keep Forgetting",
      "Redo 1 WKB setup",
      "Redo 1 perturbation recognition drill",
      "Redo 1 variational minimisation",
      "Redo 1 spin/identical-particles check",
    ],
    tags: ["QM2", "Final Review", "Critical"],
  },
  {
    id: "timeline-2026-05-11-condensed-catch-up",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-11",
    moduleId: "condensed",
    priority: "Medium",
    type: "Catch-up",
    estimatedMinutes: 60,
    title: "Catch up unfinished Topic 10-12 notes",
    details: ["Catch up unfinished Topic 10-12 notes", "Do not start past papers yet"],
    tags: ["Condensed", "Catch-up"],
  },
  {
    id: "timeline-2026-05-11-admin-logistics",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-11",
    moduleId: "admin",
    priority: "Critical",
    type: "Exam Logistics",
    estimatedMinutes: 30,
    title: "Sleep and exam logistics",
    details: ["Sleep and exam logistics"],
    tags: ["Admin"],
  },
  {
    id: "timeline-2026-05-12-qm2-exam",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-12",
    moduleId: "qm2",
    priority: "Critical",
    type: "Exam",
    estimatedMinutes: 0,
    title: "QM2 exam",
    details: ["QM2 exam"],
    tags: ["QM2", "Exam"],
  },
  {
    id: "timeline-2026-05-12-admin-rest",
    phaseId: "phase-1-before-qm2",
    plannedDate: "2026-05-12",
    moduleId: "admin",
    priority: "Light",
    type: "Rest/Admin",
    estimatedMinutes: 0,
    title: "Rest after QM2 exam",
    details: ["Rest after exam", "Admin only if needed", "No real learning"],
    tags: ["Admin", "Rest"],
  },
  {
    id: "condensed-day1-2d-free-electron-gas",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-14",
    moduleId: "condensed",
    priority: "Critical",
    type: "Section A Safety Net",
    estimatedMinutes: 50,
    title: "2D Free Electron Gas - g2D(E), EF",
    details: ["Section A safety net", "Use 2025/v3 paper logic", "Write g2D(E) and EF in 2D from memory"],
    exact: ["6CCP2000_3day_study_plan.pdf", "6CCP2000_v3.pdf - Section A"],
    tags: ["Condensed", "Section A", "Safety Net", "Critical"],
  },
  {
    id: "condensed-day1-reciprocal-lattice",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-14",
    moduleId: "condensed",
    priority: "Critical",
    type: "Section A Safety Net",
    estimatedMinutes: 50,
    title: "Reciprocal lattice vectors and BZ equivalence",
    details: ["Practise reciprocal vectors", "Check whether k-vectors differ by a reciprocal lattice vector"],
    exact: ["6CCP2000_v3.pdf - Section A Q1.2"],
    tags: ["Condensed", "Section A", "Safety Net", "Critical"],
  },
  {
    id: "condensed-day1-phonon-branch-counting",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-14",
    moduleId: "condensed",
    priority: "Critical",
    type: "Section A Safety Net",
    estimatedMinutes: 45,
    title: "Phonon branch counting",
    details: ["Primitive vs conventional cell", "Use phonon branches = 3p where p is atoms in primitive cell"],
    exact: ["6CCP2000_v3.pdf - Section A Q1.3"],
    tags: ["Condensed", "Section A", "Safety Net", "Critical"],
  },
  {
    id: "nano-paper-may-2024-part-a",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-14",
    moduleId: "nano",
    priority: "Medium",
    type: "Section A Maintenance",
    estimatedMinutes: 45,
    title: "Nano May 2024 - Part A maintenance",
    exact: ["6CCP9300 Fundamentals_of_Nanotechnology_May_Solutions_2024.pdf"],
    tags: ["Nano", "Part A", "Maintenance"],
  },
  {
    id: "condensed-day1-structure-factor",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-15",
    moduleId: "condensed",
    priority: "Critical",
    type: "Section A Safety Net",
    estimatedMinutes: 50,
    title: "Structure factor and diffraction selection rules",
    details: ["Practise FCC/BCC selection-rule logic", "Do not let old-paper order take over"],
    exact: ["6CCP2000_v3.pdf - Section A Q1.6"],
    tags: ["Condensed", "Section A", "Safety Net", "Critical"],
  },
  {
    id: "condensed-day1-optical-absorption",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-15",
    moduleId: "condensed",
    priority: "Critical",
    type: "Section A Safety Net",
    estimatedMinutes: 45,
    title: "Optical absorption, band gap, colour table",
    details: ["Read absorption onset", "Connect photon energy to colour/transparent/opaque reasoning"],
    exact: ["6CCP2000_v3.pdf - Section A Q1.4"],
    tags: ["Condensed", "Section A", "Safety Net", "Critical"],
  },
  {
    id: "condensed-day1-hysteresis",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-15",
    moduleId: "condensed",
    priority: "Critical",
    type: "Section A Safety Net",
    estimatedMinutes: 45,
    title: "Ferromagnetic hysteresis qualitative answer",
    details: ["Domains", "Saturation", "Residual magnetisation", "Keep it qualitative and exam-ready"],
    exact: ["6CCP2000_v3.pdf - Section A Q1.5"],
    tags: ["Condensed", "Section A", "Safety Net", "Critical"],
  },
  {
    id: "condensed-day1-band-filling",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-15",
    moduleId: "condensed",
    priority: "Critical",
    type: "Section A Safety Net",
    estimatedMinutes: 45,
    title: "Metal vs insulator from electron count / band filling",
    details: ["Count electrons per primitive cell", "Decide filled/partially filled bands"],
    exact: ["6CCP2000_v3.pdf - Section A Q1.7"],
    tags: ["Condensed", "Section A", "Safety Net", "Critical"],
  },
  {
    id: "nano-paper-august-2024-part-a",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-15",
    moduleId: "nano",
    priority: "Medium",
    type: "Section A Maintenance",
    estimatedMinutes: 45,
    title: "Nano August 2024 - Part A maintenance",
    exact: ["6CCP9300 Fundamentals_of_Nanotechnology_August 2024_with Solutions.pdf"],
    tags: ["Nano", "Part A", "Maintenance"],
  },
  {
    id: "condensed-day2-drude-tensor",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-16",
    moduleId: "condensed",
    priority: "Critical",
    type: "Section B Archetype",
    estimatedMinutes: 90,
    title: "Drude theory -> magneto-conductivity tensor",
    details: ["Start from Drude EOM", "Include cyclotron frequency and Hall coefficient", "Continue sub-parts even if algebra slips"],
    exact: ["6CCP2000_v3.pdf - Section B Drude-style question"],
    tags: ["Condensed", "Section B", "Archetype", "Critical"],
  },
  {
    id: "condensed-day2-bloch-kp",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-16",
    moduleId: "condensed",
    priority: "Critical",
    type: "Section B Archetype",
    estimatedMinutes: 90,
    title: "Bloch theorem + k.p perturbation theory",
    details: ["State Bloch theorem cleanly", "Set up k-dependent Hamiltonian / perturbation logic"],
    exact: ["6CCP2000_v3.pdf - Section B Bloch/k.p archetype"],
    tags: ["Condensed", "Section B", "Archetype", "Critical"],
  },
  {
    id: "condensed-day2-landau-curie-weiss",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-16",
    moduleId: "condensed",
    priority: "Critical",
    type: "Section B Archetype",
    estimatedMinutes: 90,
    title: "Landau / Curie-Weiss ferromagnet",
    details: ["ln cosh expansion", "Landau Tc", "order parameter scaling", "Sketch minima above/below Tc"],
    exact: ["2025_Q2_with_solutions.pdf", "6CCP2000_v3.pdf - Section B Landau-style question"],
    tags: ["Condensed", "Section B", "Archetype", "Critical"],
  },
  {
    id: "nano-paper-solutions-final-part-a",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-16",
    moduleId: "nano",
    priority: "Medium",
    type: "Section A Maintenance",
    estimatedMinutes: 45,
    title: "Nano Solutions final - Part A maintenance",
    exact: ["6CCP9300_Fundamentals_of_Nanotechnology_Solutions_final_.pdf"],
    tags: ["Nano", "Part A", "Maintenance"],
  },
  {
    id: "condensed-day2-backup-1d-chain",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-17",
    moduleId: "condensed",
    priority: "High",
    type: "Section B Backup",
    estimatedMinutes: 60,
    title: "Backup: 1D chain vibrations",
    details: ["Monatomic chain dispersion", "Small-k limit", "Branch counting link"],
    tags: ["Condensed", "Section B", "Backup"],
  },
  {
    id: "condensed-day2-backup-fermi-debye-hund",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-17",
    moduleId: "condensed",
    priority: "High",
    type: "Section B Backup",
    estimatedMinutes: 75,
    title: "Backup: 3D Fermi sphere, Debye heat capacity, Hund's rules",
    details: ["kF in 3D", "g3D(E)", "Debye low-T heat capacity", "Hund/Lande g recall"],
    tags: ["Condensed", "Section B", "Backup"],
  },
  {
    id: "condensed-similarity-map-targeted-practice",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-17",
    moduleId: "condensed",
    priority: "High",
    type: "Similarity Practice",
    estimatedMinutes: 90,
    title: "Use old papers only through the similarity map",
    details: [
      "A1.1 2D DOS -> 2019 Q3 / resit Q1.5 / problems_with_solutions_w_6.pdf",
      "A1.2 reciprocal lattice -> problems_with_solutions_w_3.pdf and w_4.pdf",
      "A1.3 phonons -> problems_with_solutions_w_5.pdf",
      "A1.6 structure factor -> problems_with_solutions_w_4.pdf and old CsH crystallography",
      "Do not restart the old Aug 2014-first plan",
    ],
    tags: ["Condensed", "Similarity Map", "Old Papers Demoted"],
  },
  {
    id: "nano-paper-2020-21-may-part-a",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-17",
    moduleId: "nano",
    priority: "Medium",
    type: "Section A Maintenance",
    estimatedMinutes: 45,
    title: "Nano 2020/21 May - Part A maintenance",
    exact: ["6CCP9930_Fundamentals_of_Nanotechnology_2020-2021_May_final Solutions.pdf"],
    tags: ["Nano", "Part A", "Maintenance"],
  },
  {
    id: "condensed-2025-v3-paper-part-a",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-18",
    moduleId: "condensed",
    priority: "Critical",
    type: "2025 Practice",
    estimatedMinutes: 80,
    title: "Sit 2025/v3 paper closed-book - Section A",
    details: ["Use only the rubric", "Section A safety-net rehearsal", "Do not look at solutions"],
    exact: ["6CCP2000_v3.pdf - Section A"],
    tags: ["Condensed", "2025 Paper", "Section A", "Closed Book", "Critical"],
  },
  {
    id: "condensed-2025-v3-paper-part-b",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-18",
    moduleId: "condensed",
    priority: "Critical",
    type: "2025 Practice",
    estimatedMinutes: 100,
    title: "Sit 2025/v3 paper closed-book - Section B",
    details: ["Answer all 3 Section B questions", "Follow scaffolded sub-parts", "Never skip later sub-parts"],
    exact: ["6CCP2000_v3.pdf - Section B"],
    tags: ["Condensed", "2025 Paper", "Section B", "Closed Book", "Critical"],
  },
  {
    id: "condensed-day3-mark-identify-weaknesses",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-18",
    moduleId: "condensed",
    priority: "Critical",
    type: "Mistake Repair",
    estimatedMinutes: 90,
    title: "Mark honestly and identify two weakest topics",
    details: ["Mark the 2025 paper", "Pick only two weakest topics", "Do not reopen the whole course"],
    tags: ["Condensed", "2025 Paper", "Mistake Repair", "Critical"],
  },
  {
    id: "nano-paper-final-august-2024-part-a",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-18",
    moduleId: "nano",
    priority: "Medium",
    type: "Section A Maintenance",
    estimatedMinutes: 45,
    title: "Nano final August 2024 - Part A maintenance",
    exact: ["Fundamentals of Nanotechnology final August2024.pdf"],
    tags: ["Nano", "Part A", "Maintenance"],
  },
  {
    id: "condensed-day3-revisit-two-weakest",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-19",
    moduleId: "condensed",
    priority: "Critical",
    type: "Mistake Repair",
    estimatedMinutes: 120,
    title: "Revisit only the two weakest Condensed topics",
    details: ["Use your 2025 paper marking", "Do not expand into a full-topic rabbit hole"],
    tags: ["Condensed", "Targeted Repair", "Critical"],
  },
  {
    id: "condensed-day3-q2-solutions-review",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-19",
    moduleId: "condensed",
    priority: "Critical",
    type: "Solutions Review",
    estimatedMinutes: 60,
    title: "Re-read 2025_Q2_with_solutions.pdf",
    details: ["Focus on Landau/Curie-Weiss structure", "Extract setup, not prose"],
    exact: ["2025_Q2_with_solutions.pdf"],
    tags: ["Condensed", "Q2", "Solutions", "Critical"],
  },
  {
    id: "condensed-day3-dry-fire-drude-bloch",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-19",
    moduleId: "condensed",
    priority: "Critical",
    type: "Dry Fire",
    estimatedMinutes: 60,
    title: "Dry-fire Drude tensor setup and Bloch theorem derivation",
    details: ["No notes", "Write the first two setup lines for each"],
    tags: ["Condensed", "Drude", "Bloch", "Critical"],
  },
  {
    id: "condensed-final-cheat-sheet",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-19",
    moduleId: "condensed",
    priority: "Critical",
    type: "Formula Sheet",
    estimatedMinutes: 120,
    title: "Final Condensed cheat-sheet checklist",
    details: [
      "g2D(E), EF in 2D, g3D(E), kF in 3D",
      "reciprocal lattice formula, d_hkl = 2pi/|G_hkl|",
      "phonon branches = 3p, monatomic chain dispersion",
      "NFE gap, Bloch theorem, k.p perturbation",
      "Drude EOM, cyclotron frequency, Hall coefficient",
      "FCC/BCC diffraction, Curie law, Landau Tc, ln cosh, Debye, Hund, Lande g",
    ],
    tags: ["Condensed", "Cheat Sheet", "Final Review", "Critical"],
  },
  {
    id: "nano-paper-revision-week-closed-book-part-a",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-19",
    moduleId: "nano",
    priority: "Medium",
    type: "Section A Maintenance",
    estimatedMinutes: 45,
    title: "Nano revision-week closed-book - Part A maintenance",
    exact: ["PART 1 of 6CCP9300 revision week question closed bookAmelle Zair.pdf"],
    tags: ["Nano", "Part A", "Maintenance"],
  },
  {
    id: "nano-paper-may-2024-part-b",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-20",
    moduleId: "nano",
    priority: "Medium",
    type: "Past Paper",
    estimatedMinutes: 45,
    title: "Nano May 2024 - Part B",
    exact: ["6CCP9300 Fundamentals_of_Nanotechnology_May_Solutions_2024.pdf"],
    tags: ["Nano", "Past Paper", "Part B"],
  },
  {
    id: "nano-paper-august-2024-part-b",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-20",
    moduleId: "nano",
    priority: "Medium",
    type: "Past Paper",
    estimatedMinutes: 45,
    title: "Nano August 2024 - Part B",
    exact: ["6CCP9300 Fundamentals_of_Nanotechnology_August 2024_with Solutions.pdf"],
    tags: ["Nano", "Past Paper", "Part B"],
  },
  {
    id: "nano-paper-solutions-final-part-b",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-20",
    moduleId: "nano",
    priority: "Medium",
    type: "Past Paper",
    estimatedMinutes: 45,
    title: "Nano Solutions final - Part B",
    exact: ["6CCP9300_Fundamentals_of_Nanotechnology_Solutions_final_.pdf"],
    tags: ["Nano", "Past Paper", "Part B"],
  },
  {
    id: "nano-paper-2020-21-may-part-b",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-20",
    moduleId: "nano",
    priority: "Medium",
    type: "Past Paper",
    estimatedMinutes: 45,
    title: "Nano 2020/21 May - Part B",
    exact: ["6CCP9930_Fundamentals_of_Nanotechnology_2020-2021_May_final Solutions.pdf"],
    tags: ["Nano", "Past Paper", "Part B"],
  },
  {
    id: "timeline-2026-05-20-condensed-exam",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-20",
    moduleId: "condensed",
    priority: "Critical",
    type: "Exam",
    estimatedMinutes: 0,
    title: "Condensed Matter exam",
    details: ["Condensed Matter exam"],
    tags: ["Condensed", "Exam"],
  },
  {
    id: "nano-paper-final-august-2024-part-b",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-20",
    moduleId: "nano",
    priority: "Medium",
    type: "Past Paper",
    estimatedMinutes: 45,
    title: "Nano final August 2024 - Part B",
    exact: ["Fundamentals of Nanotechnology final August2024.pdf"],
    tags: ["Nano", "Past Paper", "Part B"],
  },
  {
    id: "nano-paper-revision-week-closed-book-part-b",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-20",
    moduleId: "nano",
    priority: "Medium",
    type: "Past Paper",
    estimatedMinutes: 45,
    title: "Nano revision-week closed-book - Part B",
    exact: ["PART 1 of 6CCP9300 revision week question closed bookAmelle Zair.pdf"],
    tags: ["Nano", "Past Paper", "Part B"],
  },
  {
    id: "timeline-2026-05-21-nano-exam",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-21",
    moduleId: "nano",
    priority: "Critical",
    type: "Exam",
    estimatedMinutes: 0,
    title: "Nano exam",
    details: ["Nano exam"],
    tags: ["Nano", "Exam"],
  },
  {
    id: "timeline-2026-05-21-gr-reset-admin",
    phaseId: "phase-2-condensed-nano-war-week",
    plannedDate: "2026-05-21",
    moduleId: "grcosmo",
    priority: "Light",
    type: "Admin",
    estimatedMinutes: 0,
    title: "GR reset/admin only",
    details: ["Rest after exam", "Evening: GR reset/admin only"],
    tags: ["GR", "Admin"],
  },
  {
    id: "timeline-2026-05-22-gr-foundations-rebuild",
    phaseId: "phase-3-gr-rescue",
    plannedDate: "2026-05-22",
    moduleId: "grcosmo",
    priority: "Critical",
    type: "Week-Based Study",
    estimatedMinutes: 270,
    title: "Week 1-4 rapid rebuild",
    details: [
      "Read/review Weeks 1-4 lecture/chapter notes",
      "Do/redo matching problem sheets from Weeks 1-4",
      "Focus on manifolds, tensors, metrics, Christoffels, and geodesics",
      "Redo grc-combined-exam-25.pdf - Q2(a)",
    ],
    exact: ["grc-combined-exam-25.pdf - Q2(a)"],
    tags: ["GR", "Weeks 1-4", "Foundations", "Critical"],
  },
  {
    id: "timeline-2026-05-23-gr-week-5-full-sweep",
    phaseId: "phase-3-gr-rescue",
    plannedDate: "2026-05-23",
    moduleId: "grcosmo",
    priority: "Critical",
    type: "Week-Based Study",
    estimatedMinutes: 270,
    title: "Week 5 full sweep",
    details: [
      "Read Week 5 lecture/chapter notes",
      "Do Week 5 matching problem sheet",
      "Redo grc-combined-exam-25.pdf - Q2(b)-(c)",
    ],
    exact: ["grc-combined-exam-25.pdf - Q2(b)-(c)"],
    tags: ["GR", "Week 5", "Curvature", "Critical"],
  },
  {
    id: "timeline-2026-05-24-gr-week-6-full-sweep",
    phaseId: "phase-3-gr-rescue",
    plannedDate: "2026-05-24",
    moduleId: "grcosmo",
    priority: "Critical",
    type: "Week-Based Study",
    estimatedMinutes: 270,
    title: "Week 6 full sweep",
    details: [
      "Read Week 6 lecture/chapter notes",
      "Do Week 6 matching problem sheet",
      "Redo problems-7.pdf - Problem 1",
      "Redo 2025 GR paper - Section B Q2(a)-(c)",
    ],
    exact: ["problems-7.pdf - Problem 1", "2025 GR paper - Section B Q2(a)-(c)"],
    tags: ["GR", "Week 6", "Schwarzschild", "Critical"],
  },
  {
    id: "timeline-2026-05-25-gr-week-7-full-sweep",
    phaseId: "phase-3-gr-rescue",
    plannedDate: "2026-05-25",
    moduleId: "grcosmo",
    priority: "Critical",
    type: "Week-Based Study",
    estimatedMinutes: 270,
    title: "Week 7 full sweep",
    details: [
      "Read Week 7 lecture/chapter notes",
      "Do Week 7 matching problem sheet",
      "Redo problems-7.pdf - Problem 2",
      "Redo grc-combined-exam-25.pdf - Q3(a)-(b)",
    ],
    exact: ["grc-combined-exam-25.pdf - Q3(a)-(b)", "problems-7.pdf - Problem 2(a)-(c)"],
    tags: ["GR", "Week 7", "Penrose", "Causality", "Critical"],
  },
  {
    id: "timeline-2026-05-26-gr-weeks-8-10-cosmology-sweep",
    phaseId: "phase-3-gr-rescue",
    plannedDate: "2026-05-26",
    moduleId: "grcosmo",
    priority: "Critical",
    type: "Week-Based Study",
    estimatedMinutes: 270,
    title: "Weeks 8-10 cosmology sweep",
    details: [
      "Read cosmology lecture/chapter notes",
      "Do cosmology problems if available",
      "Redo grc-combined-exam-25.pdf - Q1.6-Q1.7",
      "Redo grc-combined-exam-25.pdf - Q4(a)-(c)",
      "Final GR/Cosmology formula and diagram sheet",
    ],
    exact: ["grc-combined-exam-25.pdf - Section A Q1.6-Q1.7", "grc-combined-exam-25.pdf - Section B Q4(a)-(c)"],
    tags: ["Cosmology", "Weeks 8-10", "Final Review", "Critical"],
  },
  {
    id: "timeline-2026-05-27-gr-exam",
    phaseId: "phase-3-gr-rescue",
    plannedDate: "2026-05-27",
    moduleId: "grcosmo",
    priority: "Critical",
    type: "Exam",
    estimatedMinutes: 0,
    title: "GR/Cosmology exam",
    details: ["GR/Cosmology exam"],
    tags: ["GR", "Exam"],
  },
];
